name: Terraform Deploy 

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
       
    defaults:
     run:
      working-directory: infra
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region:  eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check
    
      - name: Terraform Validate
        run: terraform validate 
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      
      - name: Terraform Apply 
        run: terraform apply -auto-approve tfplan
 